version: 2

models:
  - name: fct_energy_period
    description: "Table de fait : consommation par période (HP/HC/Total) + estimation de coût."
    columns:
      - name: period_start
        description: "Début de période (date)."
        tests: [not_null]
      - name: period_end
        description: "Fin de période (date)."
        tests: [not_null]
      - name: period_days
        description: "Nombre de jours dans la période."
      - name: kwh_hp
        description: "Consommation HP sur la période (kWh)."
      - name: kwh_hc
        description: "Consommation HC sur la période (kWh)."
      - name: kwh_total
        description: "Consommation totale sur la période (kWh)."
      - name: kwh_per_day_est
        description: "Consommation moyenne estimée par jour sur la période (kWh/j)."
      - name: hp_eur_per_kwh
        description: "Tarif HP utilisé pour l’estimation (€/kWh)."
      - name: hc_eur_per_kwh
        description: "Tarif HC utilisé pour l’estimation (€/kWh)."
      - name: cost_est_eur
        description: "Coût estimé total sur la période (en €)."

  - name: agg_energy_calendar_month_est
    description: "Agrégat mensuel : consommation et coût estimés par mois."